ALTER TABLE therapists ADD COLUMN IF NOT EXISTS age INTEGER;
ALTER TABLE therapists ADD COLUMN IF NOT EXISTS height INTEGER;
ALTER TABLE therapists ADD COLUMN IF NOT EXISTS bust INTEGER;
ALTER TABLE therapists ADD COLUMN IF NOT EXISTS waist INTEGER;
ALTER TABLE therapists ADD COLUMN IF NOT EXISTS hip INTEGER;
